spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/voyage?useSSL=false&serverTimezone=Asia/Seoul
        username: ssafy
        password: ssafy
    jpa:
        database: mysql
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        open-in-view: false
    logging:
        level:
            org:
                hibernate:
                    SQL: trace
            com:
                amazonaws:
                    util:
                        EC2MetadataUtils: error

# JWT
jwt:
    secret: ${JWT_SECRET}
    token:
        access:
#            expiration: 300000 # 5분
            expiration: 86_400_000 # 1일
            header: Authorization
        refresh:
            expiration: 604_800_000 # 7일 (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> d) * 7L(d -> w))
            header: Authorization-refresh

# S3
cloud:
    aws:
        credentials:
            accessKey: ${AWS_ACCESS_KEY}
            secretKey: ${AWS_SECRET_KEY}
        s3:
            bucket: ${AWS_S3_BUCKET}
        region:
            static: ${AWS_REGION_STATIC}
        stack:
            auto: false
